name: "🐛 Report a Bug in the Kitchen"
description: Something went wrong in the café? Let us know!
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what went wrong
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What should have been served
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Recipe to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How bad is it?
      options:
        - "Minor (wrong milk)"
        - "Medium (cold coffee)"
        - "Critical (kitchen fire 🔥)"
    validations:
      required: true
